hooks.c: Fix build with glibc-2.26
* add missing sys/uio.h include for writev
* replace cfree with free as the cfree man says:
  This  function  should  never  be used.  Use free(3) instead.
  Starting with version 2.26, it has been removed from glibc.
* fixes:
  hooks.c: At top level:
  hooks.c:2428:26: error: 'cfree' undeclared here (not in a function); did you mean 'free'?
       HOOK_DIRECT_NO_DEBUG(cfree),
                          ^
  hooks.c:2675:26: error: 'writev' undeclared here (not in a function); did you mean 'write'?
       HOOK_DIRECT_NO_DEBUG(writev),
                            ^

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>